name: share_and_open_url
description: "share_and_open_url_plugin provides functionality for sharing text and opening URLs. It allows users to easily share content and quickly access web links."
version: 0.0.7
homepage: https://github.com/bedirhanssaglam/share_and_open_url_plugin
repository: https://github.com/bedirhanssaglam/share_and_open_url_plugin
issue_tracker: https://github.com/bedirhanssaglam/share_and_open_url_plugin/issues
topics: [share, url, plugin]
platforms:
  android:
  ios:

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.share.and.open.url.share_and_open_url
        pluginClass: ShareAndOpenUrlPlugin
      ios:
        pluginClass: ShareAndOpenUrlPlugin