name: share_and_open_url
description: "A Flutter plugin for sharing text and opening URLs."
version: 0.0.1
homepage: https://github.com/bedirhanssaglam/share_and_open_url_plugin
repository: https://github.com/bedirhanssaglam/share_and_open_url_plugin
issue_tracker: https://github.com/bedirhanssaglam/share_and_open_url_plugin/issues

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.share.and.open.url.share_and_open_url
        pluginClass: ShareAndOpenUrlPlugin
      ios:
        pluginClass: ShareAndOpenUrlPlugin